import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getAuthUserId } from '@/lib/get-auth'

// POST /api/whatsapp-invoice - generate WhatsApp share link for an invoice
export async function POST(req: NextRequest) {
  try {
    const { userId, error } = await getAuthUserId()
    if (error || !userId) return error || NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { transactionId } = await req.json()

    // Verify transaction belongs to this user
    const transaction = await db.transaction.findFirst({
      where: { id: transactionId, userId },
      include: { items: true, party: true },
    })

    if (!transaction) {
      return NextResponse.json({ error: 'Transaction not found' }, { status: 404 })
    }

    const setting = await db.setting.findUnique({ where: { userId } })

    // Build invoice text
    const lines: string[] = []
    lines.push('*EkBook Invoice*')
    lines.push('')
    lines.push(`Shop: ${setting?.shopName || 'My Shop'}`)
    if (setting?.phone) lines.push(`Phone: ${setting.phone}`)
    lines.push(`Invoice: ${transaction.invoiceNo || transaction.id.slice(-8)}`)
    lines.push(`Date: ${transaction.date.toLocaleDateString('en-IN')}`)
    lines.push('')

    if (transaction.party) {
      lines.push(`Bill To: ${transaction.party.name}`)
      if (transaction.party.phone) lines.push(`Phone: ${transaction.party.phone}`)
      lines.push('')
    }

    lines.push('*Items:*')
    transaction.items.forEach((item, i) => {
      lines.push(`${i + 1}. ${item.productName}`)
      lines.push(`   ${item.quantity} × ₹${item.unitPrice.toFixed(2)} = ₹${item.total.toFixed(2)}`)
    })
    lines.push('')

    lines.push(`Subtotal: ₹${transaction.subtotal.toFixed(2)}`)
    if (transaction.discountAmount > 0) {
      lines.push(`Discount: -₹${transaction.discountAmount.toFixed(2)}`)
    }
    if (transaction.cgst > 0) lines.push(`CGST: ₹${transaction.cgst.toFixed(2)}`)
    if (transaction.sgst > 0) lines.push(`SGST: ₹${transaction.sgst.toFixed(2)}`)
    if (transaction.igst > 0) lines.push(`IGST: ₹${transaction.igst.toFixed(2)}`)
    lines.push(`*Total: ₹${transaction.totalAmount.toFixed(2)}*`)
    lines.push(`Paid: ₹${transaction.paidAmount.toFixed(2)}`)

    const due = transaction.totalAmount - transaction.paidAmount
    if (due > 0) {
      lines.push(`*Balance Due: ₹${due.toFixed(2)}*`)
    }

    lines.push('')
    lines.push('Thank you for your business! 🙏')
    lines.push('')
    lines.push('_Generated by EkBook_')

    const message = encodeURIComponent(lines.join('\n'))

    // Build WhatsApp URL
    let whatsappUrl: string
    if (transaction.party?.phone) {
      // Indian numbers: strip leading 0, add 91
      let phone = transaction.party.phone.replace(/\D/g, '')
      if (phone.length === 10) phone = '91' + phone
      whatsappUrl = `https://wa.me/${phone}?text=${message}`
    } else {
      whatsappUrl = `https://wa.me/?text=${message}`
    }

    return NextResponse.json({
      success: true,
      whatsappUrl,
      message: lines.join('\n'),
    })
  } catch (error) {
    console.error('WhatsApp invoice error:', error)
    return NextResponse.json({ error: 'Failed to generate invoice' }, { status: 500 })
  }
}
