#!/usr/bin/env python3
"""Add Gujarati, Marathi, Tamil, Telugu translations to i18n.ts"""

FILE = '/home/z/my-project/src/lib/i18n.ts'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update Language type
content = content.replace(
    "export type Language = 'en' | 'hi'",
    "export type Language = 'en' | 'hi' | 'gu' | 'mr' | 'ta' | 'te'"
)

# 2. Read the Hindi section to get all keys
import re
hi_start = content.find("  hi: {")
hi_end = content.find("  },", hi_start)
hi_section = content[hi_start:hi_end]

# Extract all keys from Hindi section
keys = re.findall(r"'([^']+)':\s*'([^']*)'", hi_section)

# 3. Define translations for each language
# Using simple, everyday language (not formal/literary)
# Key: same key as English/Hindi
# Value: simple, colloquial translation

gujarati = {
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.scanner': 'AI બિલ સ્કેનર',
    'nav.sales': 'વેચાણ',
    'nav.purchases': 'ખરીદી',
    'nav.inventory': 'સ્ટોક',
    'nav.income': 'આવક અને ખર્ચ',
    'nav.parties': 'ગ્રાહકો',
    'nav.reports': 'રિપોર્ટ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.pro_tip': 'ટીપ',
    'nav.pro_tip_desc': 'AI સ્કેનરથી 5 સેકન્ડમાં બિલ ઉમેરો.',
    'nav.collapse': 'મેનુ બંધ કરો',
    'nav.expand': 'મેનુ ખોલો',
    'nav.smart_ledger': "ભારતનું સ્માર્ટ લેજર",
    'dash.greeting': 'નમસ્તે',
    'dash.today_revenue': "આજની આવક",
    'dash.today_profit': "આજનો નફો",
    'dash.sales_today': 'આજનું વેચાણ',
    'dash.revenue': 'આવક',
    'dash.net_profit': 'ચોખ્ખો નફો',
    'dash.receivable': 'વસૂલ (ગ્રાહક પર)',
    'dash.payable': 'ચૂકવવાપાત્ર (પુરવઠાદાર પર)',
    'dash.stock_value': 'સ્ટોકની કિંમત',
    'dash.gst_payable': 'GST ચૂકવવાનું',
    'dash.business_overview': 'બિઝનેસ ઝાંખી',
    'dash.filter_hint': 'તારીખ પ્રમાણે ફિલ્ટર કરો',
    'dash.sales_trend': 'વેચાણ અને નફો ટ્રેન્ડ',
    'dash.top_products': 'ટોચની વસ્તુઓ',
    'dash.payment_modes': 'ચૂકવણી પદ્ધતિ',
    'dash.category_breakdown': 'કેટેગરી પ્રમાણે વેચાણ',
    'dash.low_stock': 'ઓછો સ્ટોક',
    'dash.recent_transactions': 'તાજા વેચાણ',
    'dash.gst_summary': 'GST સારાંશ',
    'dash.smart_insights': 'સ્માર્ટ ઇનસાઇટ્સ',
    'dash.view_all': 'બધું જુઓ',
    'dash.manage': 'મેનેજ',
    'dash.full_report': 'પૂર્ણ રિપોર્ટ',
    'dash.profit_trend': 'નફો ટ્રેન્ડ',
    'dash.scan_bill': 'બિલ સ્કેન કરો',
    'dash.today_made': 'આજે તમે કમાયા',
    'dash.from': 'માંથી',
    'dash.sales_word': 'વેચાણ',
    'dash.all_clear': 'બધું ઠીક છે!',
    'dash.no_alerts': 'કોઈ ચેતવણી નહીં - બિઝનેસ સરળ ચાલી રહ્યું છે.',
    'dash.need_restock': 'વસ્તુઓ ફરી ભરવાની જરૂર',
    'dash.out_of_stock': 'સ્ટોક ખતમ',
    'dash.low_stock_short': 'ઓછો',
    'dash.latest_activity': 'તાજી પ્રવૃત્તિ',
    'action.new_sale': 'નવું વેચાણ',
    'action.new_purchase': 'નવી ખરીદી',
    'action.new_entry': 'નવી એન્ટ્રી',
    'action.add_product': 'વસ્તુ ઉમેરો',
    'action.add_party': 'ગ્રાહક ઉમેરો',
    'action.scan_bill': 'બિલ સ્કેન કરો',
    'action.sign_out': 'બહાર નીકળો',
    'action.save': 'સાચવો',
    'action.cancel': 'રદ કરો',
    'action.delete': 'કાઢી નાખો',
    'action.edit': 'સુધારો',
    'action.print': 'પ્રિન્ટ',
    'action.download': 'ડાઉનલોડ',
    'common.profit': 'નફો',
    'common.loss': 'ખોટ',
    'common.total': 'કુલ',
    'common.subtotal': 'પેટાકુલ',
    'common.discount': 'છૂટ',
    'common.paid': 'ચૂકવેલ',
    'common.due': 'બાકી',
    'common.date': 'તારીખ',
    'common.party': 'ગ્રાહક',
    'common.product': 'વસ્તુ',
    'common.quantity': 'જથ્થો',
    'common.price': 'ભાવ',
    'common.amount': 'રકમ',
    'common.category': 'કેટેગરી',
    'common.search': 'શોધો',
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.no_data': 'કોઈ ડેટા નહીં',
    'common.save_sale': 'વેચાણ સાચવો',
    'common.save_purchase': 'ખરીદી સાચવો',
    'common.cancel': 'રદ કરો',
    'stat.total_sales': 'કુલ વેચાણ',
    'stat.total_purchases': 'કુલ ખરીદી',
    'stat.total_income': 'કુલ આવક',
    'stat.total_expenses': 'કુલ ખર્ચ',
    'stat.gross_profit': 'કુલ નફો',
    'stat.net_cashflow': 'ચોખ્ખી રોકડ',
    'stat.paid': 'ચૂકવેલ',
    'stat.outstanding': 'બાકી',
    'stat.total_products': 'કુલ વસ્તુઓ',
    'stat.stock_value': 'સ્ટોક કિંમત',
    'stat.potential_profit': 'સંભવિત નફો',
    'stat.low_out_stock': 'ઓછો/ખતમ સ્ટોક',
    'stat.margin': 'માર્જિન',
    'inv.search_placeholder': 'વસ્તુ શોધો...',
    'inv.all_products': 'બધી વસ્તુઓ',
    'inv.low_stock': 'ઓછો સ્ટોક',
    'inv.out_stock': 'સ્ટોક ખતમ',
    'inv.categories': 'કેટેગરી',
    'settings.profile': 'પ્રોફાઇલ',
    'settings.features': 'ફીચર્સ',
    'settings.features_desc': 'જે જોઈએ તે ચાલુ રાખો',
    'settings.reset_features': 'રીસેટ',
    'settings.about': 'BahiKhata Pro વિશે',
    'auth.sign_in': 'લોગિન',
    'auth.sign_up': 'નવું ખાતું બનાવો',
    'auth.email': 'ઈમેઈલ',
    'auth.password': 'પાસવર્ડ',
    'auth.name': 'તમારું નામ',
    'auth.welcome': 'BahiKhata Pro માં સ્વાગત છે',
    'auth.india_smart': "ભારતનું સ્માર્ટ લેજર",
    'auth.data_secure': 'તમારો ડેટા સુરક્ષિત છે. દરેક દુકાનદારનો ડેટા અલગ.',
}

marathi = {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.scanner': 'AI बिल स्कॅनर',
    'nav.sales': 'विक्री',
    'nav.purchases': 'खरेदी',
    'nav.inventory': 'स्टॉक',
    'nav.income': 'उत्पन्न आणि खर्च',
    'nav.parties': 'ग्राहक',
    'nav.reports': 'अहवाल',
    'nav.settings': 'सेटिंग्ज',
    'nav.pro_tip': 'टिप',
    'nav.pro_tip_desc': 'AI स्कॅनरने 5 सेकंडात बिल जोडा.',
    'nav.collapse': 'मेनू बंद करा',
    'nav.expand': 'मेनू उघडा',
    'nav.smart_ledger': "भारताचे स्मार्ट लेजर",
    'dash.greeting': 'नमस्कार',
    'dash.today_revenue': "आजचे उत्पन्न",
    'dash.today_profit': "आजचा नफा",
    'dash.sales_today': 'आजची विक्री',
    'dash.revenue': 'उत्पन्न',
    'dash.net_profit': 'निव्वळ नफा',
    'dash.receivable': 'वसूल (ग्राहकांकडून)',
    'dash.payable': 'देय (पुरवठादारांना)',
    'dash.stock_value': 'स्टॉकचे मूल्य',
    'dash.gst_payable': 'GST देय',
    'dash.business_overview': 'व्यवसाय आढावा',
    'dash.filter_hint': 'तारीख प्रमाणे फिल्टर करा',
    'dash.sales_trend': 'विक्री आणि नफा ट्रेंड',
    'dash.top_products': 'टॉप वस्तू',
    'dash.payment_modes': 'पेमेंट पद्धत',
    'dash.category_breakdown': 'कॅटेगरी प्रमाणे विक्री',
    'dash.low_stock': 'कमी स्टॉक',
    'dash.recent_transactions': 'अलीकडील विक्री',
    'dash.gst_summary': 'GST सारांश',
    'dash.smart_insights': 'स्मार्ट इनसाइट्स',
    'dash.view_all': 'सर्व पहा',
    'dash.manage': 'मॅनेज',
    'dash.full_report': 'संपूर्ण अहवाल',
    'dash.profit_trend': 'नफा ट्रेंड',
    'dash.scan_bill': 'बिल स्कॅन करा',
    'dash.today_made': 'आज तुम्ही कमवले',
    'dash.from': 'पासून',
    'dash.sales_word': 'विक्री',
    'dash.all_clear': 'सर्व ठीक आहे!',
    'dash.no_alerts': 'कोणताही इशारा नाही - व्यवसाय व्यवस्थित चालू आहे.',
    'dash.need_restock': 'वस्तू पुन्हा भरायच्या आहेत',
    'dash.out_of_stock': 'स्टॉक संपला',
    'dash.low_stock_short': 'कमी',
    'dash.latest_activity': 'अलीकडील क्रिया',
    'action.new_sale': 'नवीन विक्री',
    'action.new_purchase': 'नवीन खरेदी',
    'action.new_entry': 'नवीन एन्ट्री',
    'action.add_product': 'वस्तू जोडा',
    'action.add_party': 'ग्राहक जोडा',
    'action.scan_bill': 'बिल स्कॅन करा',
    'action.sign_out': 'बाहेर पडा',
    'action.save': 'जतन करा',
    'action.cancel': 'रद्द करा',
    'action.delete': 'हटवा',
    'action.edit': 'संपादन',
    'action.print': 'प्रिंट',
    'action.download': 'डाउनलोड',
    'common.profit': 'नफा',
    'common.loss': 'तोटा',
    'common.total': 'एकूण',
    'common.subtotal': 'उपएकूण',
    'common.discount': 'सूट',
    'common.paid': 'भरले',
    'common.due': 'बाकी',
    'common.date': 'तारीख',
    'common.party': 'ग्राहक',
    'common.product': 'वस्तू',
    'common.quantity': 'प्रमाण',
    'common.price': 'किंमत',
    'common.amount': 'रक्कम',
    'common.category': 'कॅटेगरी',
    'common.search': 'शोधा',
    'common.loading': 'लोड होत आहे...',
    'common.no_data': 'डेटा नाही',
    'common.save_sale': 'विक्री जतन करा',
    'common.save_purchase': 'खरेदी जतन करा',
    'common.cancel': 'रद्द करा',
    'stat.total_sales': 'एकूण विक्री',
    'stat.total_purchases': 'एकूण खरेदी',
    'stat.total_income': 'एकूण उत्पन्न',
    'stat.total_expenses': 'एकूण खर्च',
    'stat.gross_profit': 'एकूण नफा',
    'stat.net_cashflow': 'निव्वळ रोख',
    'stat.paid': 'भरले',
    'stat.outstanding': 'बाकी',
    'stat.total_products': 'एकूण वस्तू',
    'stat.stock_value': 'स्टॉक मूल्य',
    'stat.potential_profit': 'संभाव्य नफा',
    'stat.low_out_stock': 'कमी/संपलेला स्टॉक',
    'stat.margin': 'मार्जिन',
    'inv.search_placeholder': 'वस्तू शोधा...',
    'inv.all_products': 'सर्व वस्तू',
    'inv.low_stock': 'कमी स्टॉक',
    'inv.out_stock': 'स्टॉक संपला',
    'inv.categories': 'कॅटेगरी',
    'settings.profile': 'प्रोफाइल',
    'settings.features': 'फीचर्स',
    'settings.features_desc': 'जे हवे ते चालू ठेवा',
    'settings.reset_features': 'रीसेट',
    'settings.about': 'BahiKhata Pro बद्दल',
    'auth.sign_in': 'लॉगिन',
    'auth.sign_up': 'नवीन खाते तयार करा',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.name': 'तुमचे नाव',
    'auth.welcome': 'BahiKhata Pro मध्ये स्वागत आहे',
    'auth.india_smart': "भारताचे स्मार्ट लेजर",
    'auth.data_secure': 'तुमचा डेटा सुरक्षित आहे. प्रत्येक दुकानदाराचा डेटा स्वतंत्र.',
}

tamil = {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.scanner': 'AI பில் ஸ்கேனர்',
    'nav.sales': 'விற்பனை',
    'nav.purchases': 'கொள்முதல்',
    'nav.inventory': 'ஸ்டாக்',
    'nav.income': 'வருவாய் மற்றும் செலவு',
    'nav.parties': 'வாடிக்கையாளர்கள்',
    'nav.reports': 'அறிக்கை',
    'nav.settings': 'அமைப்புகள்',
    'nav.pro_tip': 'குறிப்பு',
    'nav.pro_tip_desc': 'AI ஸ்கேனர் மூலம் 5 விநாடியில் பில் சேர்க்கவும்.',
    'nav.collapse': 'மெனு மூடு',
    'nav.expand': 'மெனு திற',
    'nav.smart_ledger': "இந்தியாவின் ஸ்மார்ட் லெட்ஜர்",
    'dash.greeting': 'வணக்கம்',
    'dash.today_revenue': "இன்றைய வருவாய்",
    'dash.today_profit': "இன்றைய லாபம்",
    'dash.sales_today': 'இன்றைய விற்பனை',
    'dash.revenue': 'வருவாய்',
    'dash.net_profit': 'நிகர லாபம்',
    'dash.receivable': 'வசூல் (வாடிக்கையாளர்கள்)',
    'dash.payable': 'செலுத்த வேண்டியது (வழங்குநர்கள்)',
    'dash.stock_value': 'ஸ்டாக் மதிப்பு',
    'dash.gst_payable': 'GST செலுத்த வேண்டியது',
    'dash.business_overview': 'வணிக கண்ணோட்டம்',
    'dash.filter_hint': 'தேதி வாரியாக வடிகட்டவும்',
    'dash.sales_trend': 'விற்பனை மற்றும் லாப டிரெண்ட்',
    'dash.top_products': 'சிறந்த தயாரிப்புகள்',
    'dash.payment_modes': 'கட்டண முறை',
    'dash.category_breakdown': 'கேட்டகரி வாரி விற்பனை',
    'dash.low_stock': 'குறைந்த ஸ்டாக்',
    'dash.recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
    'dash.gst_summary': 'GST சுருக்கம்',
    'dash.smart_insights': 'ஸ்மார்ட் இன்சைட்ஸ்',
    'dash.view_all': 'அனைத்தையும் பார்',
    'dash.manage': 'நிர்வகி',
    'dash.full_report': 'முழு அறிக்கை',
    'dash.profit_trend': 'லாப டிரெண்ட்',
    'dash.scan_bill': 'பில் ஸ்கேன்',
    'dash.today_made': 'இன்று நீங்கள் சம்பாதித்தது',
    'dash.from': 'இலிருந்து',
    'dash.sales_word': 'விற்பனை',
    'dash.all_clear': 'எல்லாம் சரி!',
    'dash.no_alerts': 'எச்சரிக்கை இல்லை - உங்கள் வணிகம் சிறப்பாக இயங்குகிறது.',
    'dash.need_restock': 'தயாரிப்புகள் மீண்டும் நிரப்ப வேண்டும்',
    'dash.out_of_stock': 'ஸ்டாக் தீர்ந்தது',
    'dash.low_stock_short': 'குறைந்த',
    'dash.latest_activity': 'சமீபத்திய செயல்பாடு',
    'action.new_sale': 'புதிய விற்பனை',
    'action.new_purchase': 'புதிய கொள்முதல்',
    'action.new_entry': 'புதிய என்ட்ரி',
    'action.add_product': 'தயாரிப்பு சேர்க்கவும்',
    'action.add_party': 'வாடிக்கையாளர் சேர்க்கவும்',
    'action.scan_bill': 'பில் ஸ்கேன்',
    'action.sign_out': 'வெளியேறு',
    'action.save': 'சேமி',
    'action.cancel': 'ரத்து',
    'action.delete': 'நீக்கு',
    'action.edit': 'திருத்து',
    'action.print': 'அச்சிடு',
    'action.download': 'பதிவிறக்கம்',
    'common.profit': 'லாபம்',
    'common.loss': 'நட்டம்',
    'common.total': 'மொத்தம்',
    'common.subtotal': 'உப மொத்தம்',
    'common.discount': 'தள்ளு',
    'common.paid': 'செலுத்தப்பட்டது',
    'common.due': 'நிலுவை',
    'common.date': 'தேதி',
    'common.party': 'வாடிக்கையாளர்',
    'common.product': 'தயாரிப்பு',
    'common.quantity': 'அளவு',
    'common.price': 'விலை',
    'common.amount': 'தொகை',
    'common.category': 'கேட்டகரி',
    'common.search': 'தேடு',
    'common.loading': 'ஏற்றுகிறது...',
    'common.no_data': 'தரவு இல்லை',
    'common.save_sale': 'விற்பனை சேமி',
    'common.save_purchase': 'கொள்முதல் சேமி',
    'common.cancel': 'ரத்து',
    'stat.total_sales': 'மொத்த விற்பனை',
    'stat.total_purchases': 'மொத்த கொள்முதல்',
    'stat.total_income': 'மொத்த வருவாய்',
    'stat.total_expenses': 'மொத்த செலவு',
    'stat.gross_profit': 'மொத்த லாபம்',
    'stat.net_cashflow': 'நிகர பணப்புழக்கம்',
    'stat.paid': 'செலுத்தப்பட்டது',
    'stat.outstanding': 'நிலுவை',
    'stat.total_products': 'மொத்த தயாரிப்புகள்',
    'stat.stock_value': 'ஸ்டாக் மதிப்பு',
    'stat.potential_profit': 'சாத்தியமான லாபம்',
    'stat.low_out_stock': 'குறைந்த/தீர்ந்த ஸ்டாக்',
    'stat.margin': 'மார்ஜின்',
    'inv.search_placeholder': 'தயாரிப்பு தேடு...',
    'inv.all_products': 'அனைத்து தயாரிப்புகள்',
    'inv.low_stock': 'குறைந்த ஸ்டாக்',
    'inv.out_stock': 'ஸ்டாக் தீர்ந்தது',
    'inv.categories': 'கேட்டகரி',
    'settings.profile': 'சுயவிவரம்',
    'settings.features': 'அம்சங்கள்',
    'settings.features_desc': 'தேவையானதை இயக்கு',
    'settings.reset_features': 'மீட்டமை',
    'settings.about': 'BahiKhata Pro பற்றி',
    'auth.sign_in': 'உள்நுழை',
    'auth.sign_up': 'புதிய கணக்கு உருவாக்கு',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.name': 'உங்கள் பெயர்',
    'auth.welcome': 'BahiKhata Pro க்கு வரவேற்கிறோம்',
    'auth.india_smart': "இந்தியாவின் ஸ்மார்ட் லெட்ஜர்",
    'auth.data_secure': 'உங்கள் தரவு பாதுகாப்பானது. ஒவ்வொரு கடைக்கும் தனி தரவு.',
}

telugu = {
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.scanner': 'AI బిల్ స్కానర్',
    'nav.sales': 'అమ్మకాలు',
    'nav.purchases': 'కొనుగోళ్లు',
    'nav.inventory': 'స్టాక్',
    'nav.income': 'ఆదాయం మరియు ఖర్చు',
    'nav.parties': 'కస్టమర్లు',
    'nav.reports': 'నివేదిక',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.pro_tip': 'చిట్కా',
    'nav.pro_tip_desc': 'AI స్కానర్‌తో 5 సెకన్లలో బిల్ జోడించండి.',
    'nav.collapse': 'మెనూ మూసివేయి',
    'nav.expand': 'మెనూ తెరవండి',
    'nav.smart_ledger': "భారతదేశం యొక్క స్మార్ట్ లెడ్జర్",
    'dash.greeting': 'నమస్తే',
    'dash.today_revenue': "నేటి ఆదాయం",
    'dash.today_profit': "నేటి లాభం",
    'dash.sales_today': 'నేటి అమ్మకాలు',
    'dash.revenue': 'ఆదాయం',
    'dash.net_profit': 'నికర లాభం',
    'dash.receivable': 'వసూలు (కస్టమర్లు)',
    'dash.payable': 'చెల్లించాల్సింది (సరఫరాదారులు)',
    'dash.stock_value': 'స్టాక్ విలువ',
    'dash.gst_payable': 'GST చెల్లించాల్సింది',
    'dash.business_overview': 'వ్యాపార సారాంశం',
    'dash.filter_hint': 'తేదీ ప్రకారం ఫిల్టర్ చేయండి',
    'dash.sales_trend': 'అమ్మకాలు మరియు లాభం ట్రెండ్',
    'dash.top_products': 'టాప్ ఉత్పత్తులు',
    'dash.payment_modes': 'చెల్లింపు పద్ధతి',
    'dash.category_breakdown': 'కేటగిరీ వారీ అమ్మకాలు',
    'dash.low_stock': 'తక్కువ స్టాక్',
    'dash.recent_transactions': 'ఇటీవలి లావాదేవీలు',
    'dash.gst_summary': 'GST సారాంశం',
    'dash.smart_insights': 'స్మార్ట్ ఇన్‌సైట్‌లు',
    'dash.view_all': 'అన్నీ చూడండి',
    'dash.manage': 'నిర్వహించండి',
    'dash.full_report': 'పూర్తి నివేదిక',
    'dash.profit_trend': 'లాభం ట్రెండ్',
    'dash.scan_bill': 'బిల్ స్కాన్',
    'dash.today_made': 'ఈ రోజు మీరు సంపాదించారు',
    'dash.from': 'నుండి',
    'dash.sales_word': 'అమ్మకాలు',
    'dash.all_clear': 'అంతా బాగుంది!',
    'dash.no_alerts': 'హెచ్చరికలు లేవు - మీ వ్యాపారం సజావుగా నడుస్తోంది.',
    'dash.need_restock': 'ఉత్పత్తులు మళ్లీ నింపాలి',
    'dash.out_of_stock': 'స్టాక్ అయిపోయింది',
    'dash.low_stock_short': 'తక్కువ',
    'dash.latest_activity': 'ఇటీవలి కార్యాచరణ',
    'action.new_sale': 'కొత్త అమ్మకం',
    'action.new_purchase': 'కొత్త కొనుగోలు',
    'action.new_entry': 'కొత్త ఎంట్రీ',
    'action.add_product': 'ఉత్పత్తి జోడించండి',
    'action.add_party': 'కస్టమర్ జోడించండి',
    'action.scan_bill': 'బిల్ స్కాన్',
    'action.sign_out': 'బయటకు వెళ్ళండి',
    'action.save': 'సేవ్',
    'action.cancel': 'రద్దు',
    'action.delete': 'తొలగించు',
    'action.edit': 'సవరించు',
    'action.print': 'ప్రింట్',
    'action.download': 'డౌన్‌లోడ్',
    'common.profit': 'లాభం',
    'common.loss': 'నష్టం',
    'common.total': 'మొత్తం',
    'common.subtotal': 'ఉప మొత్తం',
    'common.discount': 'తగ్గింపు',
    'common.paid': 'చెల్లించారు',
    'common.due': 'మిగిలింది',
    'common.date': 'తేదీ',
    'common.party': 'కస్టమర్',
    'common.product': 'ఉత్పత్తి',
    'common.quantity': 'పరిమాణం',
    'common.price': 'ధర',
    'common.amount': 'మొత్తం',
    'common.category': 'కేటగిరీ',
    'common.search': 'వెతకండి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.no_data': 'డేటా లేదు',
    'common.save_sale': 'అమ్మకం సేవ్',
    'common.save_purchase': 'కొనుగోలు సేవ్',
    'common.cancel': 'రద్దు',
    'stat.total_sales': 'మొత్తం అమ్మకాలు',
    'stat.total_purchases': 'మొత్తం కొనుగోళ్లు',
    'stat.total_income': 'మొత్తం ఆదాయం',
    'stat.total_expenses': 'మొత్తం ఖర్చు',
    'stat.gross_profit': 'మొత్తం లాభం',
    'stat.net_cashflow': 'నికర నగదు',
    'stat.paid': 'చెల్లించారు',
    'stat.outstanding': 'మిగిలింది',
    'stat.total_products': 'మొత్తం ఉత్పత్తులు',
    'stat.stock_value': 'స్టాక్ విలువ',
    'stat.potential_profit': 'సాధ్యమైన లాభం',
    'stat.low_out_stock': 'తక్కువ/అయిపోయిన స్టాక్',
    'stat.margin': 'మార్జిన్',
    'inv.search_placeholder': 'ఉత్పత్తి వెతకండి...',
    'inv.all_products': 'అన్ని ఉత్పత్తులు',
    'inv.low_stock': 'తక్కువ స్టాక్',
    'inv.out_stock': 'స్టాక్ అయిపోయింది',
    'inv.categories': 'కేటగిరీ',
    'settings.profile': 'ప్రొఫైల్',
    'settings.features': 'ఫీచర్లు',
    'settings.features_desc': 'కావాల్సింది ఆన్ చేయండి',
    'settings.reset_features': 'రీసెట్',
    'settings.about': 'BahiKhata Pro గురించి',
    'auth.sign_in': 'లాగిన్',
    'auth.sign_up': 'కొత్త ఖాతా సృష్టించండి',
    'auth.email': 'ఇమెయిల్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.name': 'మీ పేరు',
    'auth.welcome': 'BahiKhata Pro కి స్వాగతం',
    'auth.india_smart': "భారతదేశం యొక్క స్మార్ట్ లెడ్జర్",
    'auth.data_secure': 'మీ డేటా సురక్షితం. ప్రతి దుకాణదారునికి వేరే డేటా.',
}

# 4. Build the new language sections
def build_section(lang_code, lang_name, translations_dict):
    lines = [f"  {lang_code}: {{"]
    lines.append(f"    // {lang_name}")
    for key, val in translations_dict.items():
        # Escape single quotes in values
        safe_val = val.replace("'", "\\'")
        lines.append(f"    '{key}': '{safe_val}',")
    lines.append("  },")
    return "\n".join(lines)

new_sections = "\n"
new_sections += build_section('gu', 'Gujarati', gujarati) + "\n"
new_sections += build_section('mr', 'Marathi', marathi) + "\n"
new_sections += build_section('ta', 'Tamil', tamil) + "\n"
new_sections += build_section('te', 'Telugu', telugu) + "\n"

# 5. Insert before the closing } of the translations object
# Find the last },\n} pattern (end of hi section + end of translations object)
insert_point = content.find("\n}\n\nexport function getTranslation")
content = content[:insert_point] + new_sections + content[insert_point:]

# 6. Update the useTranslation hook to accept all languages
# Already handled by the Language type change above

# 7. Update the localStorage check in use-translation.ts
# Currently only checks for 'hi' or 'en' — need to accept all

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Added 4 languages to i18n.ts")
print(f"Total translations per language: {len(gujarati)}")
